import React from 'react';
import {
  Plus,
  AlertCircle,
  ArrowRight,
  Undo2,
  Dumbbell,
  Lightbulb,
  CalendarDays,
  Camera,
  MessageCircle,
  Check,
  CircleCheck,
  CircleX,
  CloudMoon,
  CloudSun,
  TrendingUp,
  ThumbsUp,
  Globe2,
  ChevronLeft,
  ChevronRight,
  X,
  CloudOff,
  Wrench,
  Pencil,
  Circle,
  Flag,
  Flame,
  Zap,
  Footprints,
  Headphones,
  HelpCircle,
  Images,
  Info,
  Lock,
  LogOut,
  Chrome,
  Map,
  Medal,
  Moon,
  Ellipsis,
  Pause,
  Users,
  User,
  CircleUserRound,
  Play,
  Trophy,
  RefreshCw,
  RotateCcw,
  Repeat2,
  Utensils,
  Award,
  Save,
  Search,
  Send,
  Settings,
  Sparkles,
  ChartNoAxesColumn,
  Square,
  Sun,
  ArrowLeftRight,
  Clock,
  Trash2,
  TriangleAlert,
  Watch,
  Droplets,
  Home,
  Heart,
  Activity,
  Mail,
  MailOpen,
  KeyRound,
  Eye,
  EyeOff,
  BedDouble,
  Layers3,
  Share2,
  Bike,
  PersonStanding,
  MapPin,
  Wifi,
  Bug,
  FileText,
} from 'lucide-react-native';

const __ICON_HOME = Home;
const __ICON_HEART = Heart;

const ICONS = {
  add: Plus,
  'alert-circle': AlertCircle,
  'alert-circle-outline': AlertCircle,
  'arrow-forward': ArrowRight,
  'arrow-right': ArrowRight,
  'arrow-undo-outline': Undo2,
  'barbell-outline': Dumbbell,
  'bulb-outline': Lightbulb,
  'calendar-outline': CalendarDays,
  camera: Camera,
  'camera-outline': Camera,
  'chatbubble-ellipses': MessageCircle,
  checkmark: Check,
  'checkmark-circle': CircleCheck,
  'chevron-back': ChevronLeft,
  'chevron-forward': ChevronRight,
  close: X,
  'cloud-offline-outline': CloudOff,
  'cloudy-night-outline': CloudMoon,
  'partly-sunny-outline': CloudSun,
  'construct-outline': Wrench,
  'close-circle': CircleX,
  'close-circle-outline': CircleX,
  'create-outline': Pencil,
  ellipse: Circle,
  'ellipse-outline': Circle,
  fitness: Dumbbell,
  'fitness-outline': Dumbbell,
  flag: Flag,
  'flag-outline': Flag,
  flame: Flame,
  'flame-outline': Flame,
  flash: Zap,
  'flash-outline': Zap,
  'footsteps-outline': Footprints,
  'headset-outline': Headphones,
  'help-circle-outline': HelpCircle,
  'images-outline': Images,
  'information-circle-outline': Info,
  'lock-closed': Lock,
  'log-out-outline': LogOut,
  'logo-google': Chrome,
  'map-outline': Map,
  'medal-outline': Medal,
  'moon-outline': Moon,
  'options-outline': Ellipsis,
  pause: Pause,
  'people-outline': Users,
  person: User,
  'person-circle-outline': CircleUserRound,
  play: Play,
  'podium-outline': Trophy,
  refresh: RefreshCw,
  'refresh-circle': RefreshCw,
  'repeat-outline': Repeat2,
  'restaurant-outline': Utensils,
  'ribbon-outline': Award,
  'save-outline': Save,
  search: Search,
  'search-outline': Search,
  send: Send,
  'settings-outline': Settings,
  sparkles: Sparkles,
  'sparkles-outline': Sparkles,
  'stats-chart-outline': ChartNoAxesColumn,
  stop: Square,
  'sunny-outline': Sun,
  'swap-horizontal': ArrowLeftRight,
  sync: RefreshCw,
  'time-outline': Clock,
  'trash-outline': Trash2,
  trophy: Trophy,
  walk: Footprints,
  'walk-outline': Footprints,
  warning: TriangleAlert,
  'watch-outline': Watch,
  water: Droplets,
  'water-outline': Droplets,
  home: __ICON_HOME,
  'home-outline': __ICON_HOME,
  barbell: Dumbbell,
  nutrition: Utensils,
  'nutrition-outline': Utensils,
  'bar-chart': ChartNoAxesColumn,
  'bar-chart-outline': ChartNoAxesColumn,
  'person-outline': User,
  'person-add-outline': Plus,
  'person-remove-outline': User,
  'trophy-outline': Trophy,
  'heart': __ICON_HEART,
  'heart-outline': __ICON_HEART,
  'heart-circle-outline': __ICON_HEART,
  'pulse': Activity,
  'mail-outline': Mail,
  'mail-open-outline': MailOpen,
  'lock-closed-outline': Lock,
  'key-outline': KeyRound,
  'paper-plane-outline': Send,
  'refresh-outline': RefreshCw,
  'location-outline': MapPin,
  'wifi-outline': Wifi,
  'bug-outline': Bug,
  'document-text-outline': FileText,
  'chatbubble-ellipses-outline': MessageCircle,
  'eye-outline': Eye,
  'eye-off-outline': EyeOff,
  eye: Eye,
  'eye-off': EyeOff,
  'bed-outline': BedDouble,
  'layers-outline': Layers3,
  'share-outline': Share2,
  'bicycle-outline': Bike,
  'body-outline': PersonStanding,
};

export default function LucideIcon({ name, size = 24, color = 'currentColor', strokeWidth = 2, style, ...props }) {
  const Icon = ICONS[name] || Circle;
  return <Icon size={size} color={color} strokeWidth={strokeWidth} style={style} {...props} />;
}
